version: "3.9"

services:
  backend:
    build: ./backend
    container_name: loan_backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: loan_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
